version: '3.8'

services:
  hue-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hue-manager
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - hue-network
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  hue-network:
    driver: bridge
