version: '3.8'

services:
  hue-manager:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hue-manager
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - hue-network
    network_mode: host
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:${PORT:-8080}/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  hue-network:
    driver: bridge
